/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KitchenCards: typeof import('./src/components/KitchenCards.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    Repo: typeof import('./src/components/Repo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
  }
}
