/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[project]': RouteRecordInfo<'/[project]', '/:project', { project: ParamValue<true> }, { project: ParamValue<false> }>,
    '/kitchen/': RouteRecordInfo<'/kitchen/', '/kitchen', Record<never, never>, Record<never, never>>,
    '/kitchen/[recipe]': RouteRecordInfo<'/kitchen/[recipe]', '/kitchen/:recipe', { recipe: ParamValue<true> }, { recipe: ParamValue<false> }>,
    '/kitchen2': RouteRecordInfo<'/kitchen2', '/kitchen2', Record<never, never>, Record<never, never>>,
  }
}
